### ISSUE TITLE
_ in image name does not work

### ISSUE THREAD

**Issue by sdupuis1** [laptobbe/TSMarkdownParser#15]
![test](ic_arrow_white_left.png)

the above image filename does not work, the _ is recognized as a metacharacter and stripped out.

**Comment by sdupuis1** [comment]
ic_arrow_white_left.png

**Comment by sdupuis1** [comment]
I have solved this quickly by moving the image addImageParsingWithImageFormattingBlock to the top of the standardParser parsingPairs NSArray. The proper solution would be to fix the regular expression.

**Comment by laptobbe** [comment]
Do you know what parsing block is interfering with the image parsing?

**Comment by sdupuis1** [comment]
No i didn't track it down exactly, but I suspect the emphasis would be the culprit as it uses _ . 


     On Thursday, April 23, 2015 2:13 AM, Tobias Sundstrand <notifications@github.com> wrote:
   

 Do you know what parsing block is interfering with the image parsing?—

**Comment by baldurh** [comment]
This is caused by the `TSMarkdownEmRegex` pattern and only happens if there are two or more underscores in the filename. By parsing the image before everything else, this won’t happen. #23 "fixes" this until someone has the time to dig into that pattern.

![screen shot 2015-09-09 at 13 52 03](https://cloud.githubusercontent.com/assets/1823617/9763648/3bd2e57e-56fa-11e5-8079-a49c2c8c923d.png)
(Had to remove the lookbehind for this example)
