### ISSUE TITLE
Bold at the beginning of the line is converted to list symbol

### ISSUE THREAD

**Issue by mantas** [laptobbe/TSMarkdownParser#38]
If a string starts with an emphasized or strong text, it's converted to list symbol. E.g. "\*bold\* text" ends up as "• bold* text"

It looks like moving addListParsingWithFormattingBlock to the very end of standardParser method fixes this. I'm not very familiar with markdown, so I'm not sure if it doesn't introduce some new issues.

**Comment by Coeur** [comment]
I think you are using TSMarkdownParser 1.x.
Could you give a try to TSMarkdownParser 2.0 using:
    pod 'TSMarkdownParser', :git => 'https://github.com/laptobbe/TSMarkdownParser.git', :tag => '2.0.0'

**Comment by Coeur** [comment]
Note that I recommend TSMarkdownParser 2.0 because the new defaultParser will, as a context simplification, require a space after `*` to make it a list item.

It is still possible to define rules that would support both `*some* text` as bold and `*some * text` as a list item and a star, but I dislike that a distant symbol from the beginning of the line affects the whole line rendering.

**Comment by mantas** [comment]
Yep, it works fine with the TSMarkdownParser 2.0. I must have had cached version from Cocoapods...

I'm not using the list tag at all in this app, so this is not a problem for me. Even if I would, * + space seems more than fair requirement.

By the way, awesome library. Thank you!

**Comment by Coeur** [comment]
@mantas, please note that TSMarkdownParser 2.0.1 is now ofifically available on CocoaPods
